# Generated by Django 5.0.1 on 2024-01-19 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0004_alter_account_id_alter_record_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Record',
            new_name='Transaction',
        ),
    ]
